### ISSUE TITLE
Plugin no longer works correctly with Jekyll 4.x

### ISSUE THREAD

**Issue by kusma** [jekyll/jekyll-avatar#59]
The changes to the [template rendering](https://jekyllrb.com/docs/upgrading/3-to-4/#template-rendering) in Jekyll 4 seems to have broken rendering of avatars in templates that use usernames from front-matter in pages.

### Reproduction case
https://github.com/kusma/jekyll-avatar-issue-37-repro

### Expected behavior:
foo.html gets the foo avatar rendered, and bar.html gets the bar avatar rendered.

### Actual behavor:
foo.html gets the avatar from bar.html instead.

(split out from #37)

**Comment by cherryleafroad** [comment]
This was driving me up the wall! That fixed it completely, thanks!

**Comment by ashmaroli** [comment]
Hi,
v0.8.0 has been released. Please upgrade and confirm if this issue has been resolved.
Thanks.

**Comment by kusma** [comment]
I'm no longer using Jekyll, and as such no longer this plugin. But it should be possible to test using the repro repo for anyone...

**Comment by ashmaroli** [comment]
Thank you for responding to my call nevertheless.

**Comment by MolotovCherry** [comment]
I was using the one on master before which fixed this, and it was definitely confirmed. I haven't upgraded yet, but I don't see why the upgrade would be any different than what was on master

**Comment by kusma** [comment]
That's probably a good enough reason to close this, then!
